services:
  nas-backtester-01:
    build: .
    container_name: nas-backtester-01
    networks:
      - shared_net
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"

      BT_DB_HOST: "db"
      BT_DB_PORT: "5432"
      BT_DB_USER: "backtesting-account"
      BT_DB_PASSWORD: "backtesting-account-pw"
      BT_DB_NAME: "backtesting"
      BT_DB_SSLMODE: "prefer"

      MARKET_DB_HOST: "db"
      MARKET_DB_PORT: "5432"
      MARKET_DB_USER: "backtesting-account"
      MARKET_DB_PASSWORD: "backtesting-account-pw"
      MARKET_DB_NAME: "market-data"
      MARKET_DB_SSLMODE: "prefer"

      INITIAL_EQUITY: "10000"
      SYMBOL_NAME: "NAS100"
      TIMEFRAME: "1min"
      REQUIRED_MARGIN: "0.05"
      SPREAD_POINTS: "1.5"
      POSITION_FRACTION_OF_MAX_MARGIN: "0.40"
      RISK_FRACTION_OF_USED_MARGIN: "0.03"
      REWARD_RISK_MULTIPLE: "1.5"
      LOT_STEP: "0.1"
      START_TIME_UTC: ""
      END_TIME_UTC: ""

      ACCOUNT_NUMBER: "00001"
      ACCOUNT_TYPE: "backtester"

      OUTPUT_DIR: "/app/output"
      
      LOG_LEVEL: "DEBUG"
    volumes:
      - ./output:/app/output
    command: ["python", "/app/backtest.py"]
networks:
  shared_net:
    external: true
    name: shared_net