"""Independent signal test: one hypothetical trade stream per stock.

This mode answers a different question than the portfolio simulation: how all
strategy signals performed without cash, total-position limits, or category
caps deciding which signals made it into the book.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date

import numpy as np

from .portfolio import StockTrade
from .strategy import entry_candidates, sizing_tier


@dataclass
class IndependentResult:
    days: list[date]
    trades: list[StockTrade] = field(default_factory=list)
    avg_trade_return_pct: float | None = None
    median_trade_return_pct: float | None = None
    win_rate_pct: float | None = None
    avg_holding_days: float | None = None
    n_open_trades: int = 0


def _close_trade(trade: StockTrade, exit_date: date, exit_price: float,
                 is_open: bool, reason: str) -> None:
    trade.exit_date = exit_date
    trade.exit_price = float(exit_price)
    trade.gross_return_pct = float((exit_price / trade.entry_price - 1.0) * 100)
    trade.holding_days = (exit_date - trade.entry_date).days
    trade.is_open = is_open
    trade.exit_reason = reason


def _summarize(days: list[date], trades: list[StockTrade]) -> IndependentResult:
    returns = np.array(
        [t.gross_return_pct for t in trades if t.gross_return_pct is not None],
        dtype=float,
    )
    holding_days = np.array(
        [t.holding_days for t in trades if t.holding_days is not None],
        dtype=float,
    )
    if len(returns) == 0:
        return IndependentResult(days=days, trades=trades)
    return IndependentResult(
        days=days,
        trades=trades,
        avg_trade_return_pct=float(np.mean(returns)),
        median_trade_return_pct=float(np.median(returns)),
        win_rate_pct=float(np.mean(returns > 0) * 100.0),
        avg_holding_days=float(np.mean(holding_days)) if len(holding_days) else None,
        n_open_trades=sum(1 for t in trades if t.is_open),
    )


def run_independent_trades(days: list[date], symbols: list[str],
                           categories: dict[str, str], closes: np.ndarray,
                           fresh: np.ndarray, positions: np.ndarray,
                           stress_on: np.ndarray,
                           cat_momentum: dict[str, np.ndarray],
                           weight_pct_by_tier: dict[str, float],
                           deep_threshold: float,
                           entry_confirm_days: int = 0, sl_pct: float = 0.0,
                           time_stop_days: int = 0,
                           time_stop_min_ret_pct: float = 0.0,
                           reentry_cooldown_days: int = 0) -> IndependentResult:
    """Create every trade generated by the strategy, independent per symbol.

    Entry and exit timing intentionally matches the portfolio mode: entries
    happen entry_confirm_days trading days after a flat->long flip (signal
    still long, stress gate off); exits occur at the close of a real trading
    day when the per-stock signal flips to flat, or when a stop overlay fires
    (see run_portfolio; a catastrophe-stopped symbol is locked until its
    signal resets, a time-stopped one re-enters after reentry_cooldown_days
    trading days while still long, or stays locked when that is 0).
    """
    n_days, n_sym = closes.shape
    cand = entry_candidates(positions, entry_confirm_days)
    held: dict[int, StockTrade] = {}
    entry_row: dict[int, int] = {}
    locked = np.zeros(n_sym, dtype=bool)
    cooldown = np.full(n_sym, -1, dtype=int)  # re-eligible from this row on; -1 = none
    trades: list[StockTrade] = []

    for t in range(n_days):
        locked &= positions[t] != 0
        cooldown[positions[t] == 0] = -1

        for s in [s for s, tr in held.items()
                  if fresh[t, s] and positions[t, s] == 0]:
            trade = held.pop(s)
            entry_row.pop(s, None)
            _close_trade(trade, days[t], closes[t, s], is_open=False,
                         reason="signal")

        if sl_pct > 0 or time_stop_days > 0:
            for s in list(held):
                if not fresh[t, s]:
                    continue
                ret = closes[t, s] / held[s].entry_price - 1.0
                if sl_pct > 0 and ret <= -sl_pct / 100.0:
                    trade = held.pop(s)
                    entry_row.pop(s, None)
                    _close_trade(trade, days[t], closes[t, s], is_open=False,
                                 reason="sl")
                    locked[s] = True
                elif (time_stop_days > 0
                        and t - entry_row[s] >= time_stop_days
                        and ret <= time_stop_min_ret_pct / 100.0):
                    trade = held.pop(s)
                    entry_row.pop(s, None)
                    _close_trade(trade, days[t], closes[t, s], is_open=False,
                                 reason="ts")
                    if reentry_cooldown_days > 0:
                        cooldown[s] = t + reentry_cooldown_days
                    else:
                        locked[s] = True

        if stress_on[t]:
            continue

        for s in range(n_sym):
            if s in held or locked[s] or not fresh[t, s]:
                continue
            if not (cand[t, s] or 0 <= cooldown[s] <= t):
                continue

            cat = categories[symbols[s]]
            mom = float(cat_momentum[cat][t])
            tier = sizing_tier(mom, deep_threshold)
            target_weight_pct = weight_pct_by_tier[tier]
            trade = StockTrade(
                trade_no=len(trades) + 1,
                symbol=symbols[s],
                category=cat,
                entry_date=days[t],
                exit_date=None,
                entry_price=float(closes[t, s]),
                exit_price=None,
                gross_return_pct=None,
                holding_days=None,
                target_weight_pct=target_weight_pct,
                effective_weight_pct=target_weight_pct,
                tier=tier,
                cat_mom_at_entry=None if np.isnan(mom) else mom,
                is_open=False,
            )
            trades.append(trade)
            held[s] = trade
            entry_row[s] = t
            cooldown[s] = -1

    for s, trade in held.items():
        _close_trade(trade, days[-1], closes[n_days - 1, s], is_open=True,
                     reason="open")

    return _summarize(days, trades)
