-- Clean schema for the Wei 52-week-high pullback/reclaim backtester.
-- No backward compatibility is kept for older backtest_wei_* layouts.

CREATE EXTENSION IF NOT EXISTS timescaledb;

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'market-data-account') THEN
        CREATE USER "market-data-account" WITH PASSWORD 'market-data-account-pw';
    END IF;
END
$$;

GRANT CONNECT ON DATABASE postgres TO "market-data-account";
GRANT USAGE ON SCHEMA public TO "market-data-account";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "market-data-account";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO "market-data-account";

\if :drop_all_wei_tables_on_start
DROP TABLE IF EXISTS backtest_wei_equity_daily CASCADE;
DROP TABLE IF EXISTS backtest_wei_trades CASCADE;
DROP TABLE IF EXISTS backtest_wei_signals_daily CASCADE;
DROP TABLE IF EXISTS backtest_wei_runs CASCADE;
\endif

CREATE TABLE IF NOT EXISTS backtest_wei_runs (
    run_id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    run_ts                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    strategy_version            TEXT NOT NULL,
    config_fingerprint          TEXT NOT NULL,
    run_label                   TEXT NOT NULL,
    start_date                  DATE NOT NULL,
    end_date                    DATE NOT NULL,
    warmup_calendar_days        INTEGER NOT NULL,
    high_lookback_days          INTEGER NOT NULL,
    high_recent_days            INTEGER NOT NULL,
    min_pullback_pct            NUMERIC(12,6) NOT NULL,
    ema_fast_days               INTEGER NOT NULL,
    ema_slow_days               INTEGER NOT NULL,
    ema_cross_lookback_days     INTEGER NOT NULL,
    max_entry_gap_pct           NUMERIC(12,6) NOT NULL,
    atr_days                    INTEGER NOT NULL,
    initial_stop_mode           TEXT NOT NULL,
    atr_stop_multiple           NUMERIC(12,6) NOT NULL,
    volume_sma_days             INTEGER NOT NULL,
    volume_filter_enable        BOOLEAN NOT NULL,
    ibkr_category_breadth_filter_enable BOOLEAN NOT NULL,
    ibkr_category_breadth_on_threshold NUMERIC(8,4) NOT NULL,
    ibkr_category_breadth_off_threshold NUMERIC(8,4) NOT NULL,
    ibkr_category_breadth_min_symbols INTEGER NOT NULL,
    position_size_usd           NUMERIC(18,2) NOT NULL,
    stop_loss_pct               NUMERIC(12,6) NOT NULL,
    trailing_activate_pct       NUMERIC(12,6) NOT NULL,
    trailing_loss_pct           NUMERIC(12,6) NOT NULL,
    initial_equity              NUMERIC(18,2) NOT NULL,
    allow_fractional_shares     BOOLEAN NOT NULL,
    min_price                   NUMERIC(15,4) NOT NULL,
    min_market_cap_usd          NUMERIC(20,2) NOT NULL,
    revenue_yoy_min             NUMERIC(12,6) NOT NULL,
    revenue_stale_trading_days  INTEGER NOT NULL,
    signal_count                INTEGER NOT NULL,
    trade_count                 INTEGER NOT NULL,
    final_equity                NUMERIC(18,2),
    total_pnl                   NUMERIC(18,2),
    total_return                NUMERIC(18,6),
    cagr                        NUMERIC(18,6),
    max_drawdown                NUMERIC(18,6),
    win_rate                    NUMERIC(18,6),
    profit_factor               NUMERIC(18,6),
    avg_r_multiple              NUMERIC(18,6),
    avg_holding_days            NUMERIC(18,6)
);

SELECT create_hypertable(
    'backtest_wei_runs',
    'run_ts',
    chunk_time_interval => INTERVAL '365 days',
    if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS idx_backtest_wei_runs_run_id
    ON backtest_wei_runs (run_id DESC, run_ts DESC);

CREATE INDEX IF NOT EXISTS idx_backtest_wei_runs_fingerprint
    ON backtest_wei_runs (config_fingerprint, run_ts DESC);

CREATE TABLE IF NOT EXISTS backtest_wei_signals_daily (
    run_id                      BIGINT NOT NULL,
    period_end_date             DATE NOT NULL,
    symbol                      TEXT NOT NULL,
    ibkr_industry               TEXT,
    ibkr_category               TEXT,
    close                       NUMERIC(15,4) NOT NULL,
    high                        NUMERIC(15,4) NOT NULL,
    volume                      NUMERIC(20,4) NOT NULL,
    alpaca_price_feed           TEXT,
    entry_ref_market_cap_usd    NUMERIC(20,2),
    entry_ref_market_cap_currency TEXT,
    market_cap_pass             BOOLEAN NOT NULL,
    revenue_ttm                 NUMERIC(20,2),
    prev_revenue_ttm            NUMERIC(20,2),
    revenue_yoy                 NUMERIC(18,6),
    revenue_pass                BOOLEAN NOT NULL,
    rolling_52w_high            NUMERIC(15,4) NOT NULL,
    is_52w_high                 BOOLEAN NOT NULL,
    had_52w_high_recent         BOOLEAN NOT NULL,
    last_52w_high_date          DATE NOT NULL,
    last_52w_high_price         NUMERIC(15,4) NOT NULL,
    bars_since_52w_high         INTEGER NOT NULL,
    pullback_low_since_52w_high NUMERIC(15,4) NOT NULL,
    pullback_from_52w_high_pct  NUMERIC(18,6) NOT NULL,
    pullback_pass               BOOLEAN NOT NULL,
    atr                         NUMERIC(15,6),
    ema_fast                    NUMERIC(15,6) NOT NULL,
    ema_slow                    NUMERIC(15,6) NOT NULL,
    prev_ema_fast               NUMERIC(15,6) NOT NULL,
    prev_ema_slow               NUMERIC(15,6) NOT NULL,
    ema_cross_up                BOOLEAN NOT NULL,
    ema_cross_down              BOOLEAN NOT NULL,
    ema_cross_recent            BOOLEAN NOT NULL,
    ema_cross_delay_days        INTEGER NOT NULL,
    ema_already_above_on_52w_high BOOLEAN NOT NULL,
    ema_entry_pass              BOOLEAN NOT NULL,
    entry_gap_pct               NUMERIC(18,6),
    entry_gap_pass              BOOLEAN NOT NULL,
    planned_entry_atr           NUMERIC(15,6),
    volume_sma50                NUMERIC(20,4) NOT NULL,
    volume_sma50_pass           BOOLEAN NOT NULL,
    volume_feed_pass            BOOLEAN NOT NULL,
    volume_pass                 BOOLEAN NOT NULL,
    ibkr_category_breadth_pct   NUMERIC(8,4),
    ibkr_category_breadth_on    BOOLEAN NOT NULL,
    ibkr_category_breadth_pass  BOOLEAN NOT NULL,
    entry_signal                BOOLEAN NOT NULL,
    planned_entry_date          DATE NOT NULL,
    planned_entry_open          NUMERIC(15,4) NOT NULL,
    created_ts                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

SELECT create_hypertable(
    'backtest_wei_signals_daily',
    'period_end_date',
    chunk_time_interval => INTERVAL '365 days',
    if_not_exists => TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_backtest_wei_signals_daily_run_symbol
    ON backtest_wei_signals_daily (run_id, period_end_date, symbol);

CREATE INDEX IF NOT EXISTS idx_backtest_wei_signals_daily_category
    ON backtest_wei_signals_daily (run_id, period_end_date DESC, ibkr_category);

CREATE TABLE IF NOT EXISTS backtest_wei_trades (
    trade_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entry_date                  DATE NOT NULL,
    run_id                      BIGINT NOT NULL,
    position_id                 INTEGER NOT NULL,
    symbol                      TEXT NOT NULL,
    ibkr_industry               TEXT,
    ibkr_category               TEXT,
    signal_date                 DATE NOT NULL,
    exit_date                   DATE NOT NULL,
    exit_reason                 TEXT NOT NULL,
    entry_price                 NUMERIC(15,4) NOT NULL,
    exit_price                  NUMERIC(15,4) NOT NULL,
    shares                      NUMERIC(20,8) NOT NULL,
    notional_usd                NUMERIC(18,2) NOT NULL,
    entry_ref_market_cap_usd    NUMERIC(20,2),
    entry_ref_market_cap_currency TEXT,
    planned_entry_atr           NUMERIC(15,6),
    initial_stop_mode           TEXT NOT NULL,
    initial_stop_price          NUMERIC(15,4) NOT NULL,
    exit_stop_price             NUMERIC(15,4) NOT NULL,
    max_price                   NUMERIC(15,4) NOT NULL,
    pnl                         NUMERIC(18,2) NOT NULL,
    return_pct                  NUMERIC(18,6) NOT NULL,
    r_multiple                  NUMERIC(18,6) NOT NULL,
    holding_days                INTEGER NOT NULL
);

SELECT create_hypertable(
    'backtest_wei_trades',
    'entry_date',
    chunk_time_interval => INTERVAL '365 days',
    if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS idx_backtest_wei_trades_run
    ON backtest_wei_trades (run_id, symbol, entry_date DESC);

CREATE INDEX IF NOT EXISTS idx_backtest_wei_trades_exit
    ON backtest_wei_trades (run_id, exit_date DESC, exit_reason);

CREATE TABLE IF NOT EXISTS backtest_wei_equity_daily (
    period_end_date             DATE NOT NULL,
    run_id                      BIGINT NOT NULL,
    equity                      NUMERIC(18,2) NOT NULL,
    realized_pnl                NUMERIC(18,2) NOT NULL,
    open_pnl                    NUMERIC(18,2) NOT NULL,
    open_positions              INTEGER NOT NULL,
    gross_exposure_usd          NUMERIC(18,2) NOT NULL,
    exposure_pct                NUMERIC(18,6) NOT NULL
);

SELECT create_hypertable(
    'backtest_wei_equity_daily',
    'period_end_date',
    chunk_time_interval => INTERVAL '365 days',
    if_not_exists => TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_backtest_wei_equity_daily_run
    ON backtest_wei_equity_daily (run_id, period_end_date);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "market-data-account";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "market-data-account";
