from __future__ import annotations


IDENTITY_COLUMNS = ("symbol", "exchange", "cik")
EARLY_CUT_LANDMARK_DAYS = (1, 2, 3)
MANAGEMENT_LANDMARK_DAYS = (5, 20, 30)
POSITION_LANDMARK_DAYS = (*EARLY_CUT_LANDMARK_DAYS, *MANAGEMENT_LANDMARK_DAYS)

CRITERION_COLUMNS = (
    "crit_price_above_ma150_200",
    "crit_ma150_above_ma200",
    "crit_ma200_rising",
    "crit_ma50_above_ma150_200",
    "crit_price_above_ma50",
    "crit_above_52w_low",
    "crit_near_52w_high",
    "crit_rs_rating",
)

SHORT_MA_SOURCE_COLUMNS = ("ma5", "ma9", "ma21")
CANDLE_BODY_WINDOWS = (1, 5, 10, 15, 20, 30)
CANDLE_BODY_SOURCE_COLUMNS = tuple(
    f"{direction}_candle_body_pct_{window}d"
    for window in CANDLE_BODY_WINDOWS
    for direction in ("bullish", "bearish")
)
CANDLE_BODY_DERIVED_FEATURE_COLUMNS = (
    "signed_candle_body_pct_1d",
    *(
        f"candle_body_balance_pct_{window}d"
        for window in CANDLE_BODY_WINDOWS
        if window != 1
    ),
)
SHORT_MA_DERIVED_FEATURE_COLUMNS = (
    "distance_to_ma5_pct",
    "distance_to_ma9_pct",
    "distance_to_ma21_pct",
    "ma5_vs_ma9_pct",
    "ma9_vs_ma21_pct",
    "short_sma_breadth",
)
SHORT_TERM_DERIVED_FEATURE_COLUMNS = (
    *CANDLE_BODY_DERIVED_FEATURE_COLUMNS,
    *SHORT_MA_DERIVED_FEATURE_COLUMNS,
)
SHORT_TERM_STRUCTURE_FEATURE_COLUMNS = (
    "close_vs_prior_26w_high_pct",
    *CANDLE_BODY_SOURCE_COLUMNS,
    *SHORT_TERM_DERIVED_FEATURE_COLUMNS,
)

SOURCE_COLUMNS = (
    "period_end_date",
    *IDENTITY_COLUMNS,
    "price_continuity_segment",
    "currency",
    "raw_close",
    "adjusted_close",
    "adjusted_high",
    "adjusted_low",
    "adjusted_volume",
    "daily_price_change_pct",
    "adjusted_volume_sma21_prior",
    "adjusted_volume_vs_sma21_prior_ratio",
    "adjusted_volume_sma50_prior",
    "adjusted_volume_vs_sma50_prior_ratio",
    "daily_traded_notional_usd",
    "daily_traded_notional_sma21_prior_usd",
    "daily_traded_notional_vs_sma21_prior_ratio",
    "daily_traded_notional_sma50_prior_usd",
    "daily_traded_notional_vs_sma50_prior_ratio",
    "dollar_volume_63d",
    *SHORT_MA_SOURCE_COLUMNS,
    "ma50",
    "ma150",
    "ma200",
    "ma200_21_sessions_ago",
    "low_52w",
    "high_52w",
    "close_vs_prior_26w_high_pct",
    *CANDLE_BODY_SOURCE_COLUMNS,
    "rs_raw",
    "rs_rating",
    "rs_universe_size",
    "forward_5d_max_gain_pct",
    "forward_5d_max_loss_pct",
    "forward_10d_max_gain_pct",
    "forward_10d_max_loss_pct",
    "forward_20d_max_gain_pct",
    "forward_20d_max_loss_pct",
    *CRITERION_COLUMNS,
    "trend_template_pass",
)

# ``adjusted_open`` is joined from the point-in-time core market table for
# executable next-session decisions. It is intentionally not part of the
# stock_analyser source-table contract.
CALCULATION_SOURCE_COLUMNS = (*SOURCE_COLUMNS, "adjusted_open")

FUNDAMENTAL_SNAPSHOT_SOURCE_COLUMNS = (
    *IDENTITY_COLUMNS,
    "period_end_date",
    "sec_fundamental_currency",
    "sec_latest_period_end_date",
    "sec_data_available_at",
    "sec_revenue_ttm",
    "sec_operating_income_ttm",
    "sec_net_income_ttm",
    "sec_operating_cashflow_ttm",
    "sec_capex_ttm",
    "sec_free_cashflow_ttm",
    "sec_share_based_compensation_ttm",
    "sec_free_cashflow_sbc_adjusted_ttm",
    "sec_research_and_development_ttm",
    "sec_selling_general_and_admin_ttm",
    "sec_interest_expense_ttm",
    "sec_depreciation_and_amortization_ttm",
    "sec_assets",
    "sec_stockholders_equity",
    "sec_cash_and_equivalents",
    "sec_total_debt",
    "sec_current_assets",
    "sec_current_liabilities",
    "sec_inventory",
    "sec_accounts_receivable",
    "sec_accounts_payable",
    "sec_goodwill",
    "sec_intangible_assets",
    "sec_property_plant_equipment",
    "sec_shares_outstanding",
    "sec_weighted_avg_shares_diluted",
    "sec_common_stock_repurchased_ttm",
    "sec_gross_margin_ttm",
    "sec_operating_margin_ttm",
    "sec_net_margin_ttm",
    "sec_fcf_margin_ttm",
    "sec_fcf_sbc_adjusted_margin_ttm",
    "sec_debt_to_capital",
    "sec_cash_to_assets",
    "sec_current_ratio",
    "sec_accruals_ratio",
)

QUARTERLY_FUNDAMENTAL_EVENT_SOURCE_COLUMNS = (
    *IDENTITY_COLUMNS,
    "accession_number",
    "accepted_at",
    "effective_date",
    "fiscal_period_end_date",
    "diluted_eps",
    "prior_year_diluted_eps",
    "currency",
    "quarterly_revenue",
    "prior_year_quarterly_revenue",
    "quarterly_operating_income",
    "prior_year_quarterly_operating_income",
    "quarterly_net_income",
    "prior_year_quarterly_net_income",
    "quarterly_operating_margin",
    "prior_year_quarterly_operating_margin",
    "quarterly_net_margin",
    "prior_year_quarterly_net_margin",
)

EARNINGS_EVENT_SOURCE_COLUMNS = (
    *IDENTITY_COLUMNS,
    "earnings_date",
    "announcement_ts",
    "announcement_time_type",
    "source",
    "source_event_id",
    "known_as_of_ts",
    "is_confirmed",
)

MARKET_METRIC_SOURCE_COLUMNS = (
    "period_end_date",
    *IDENTITY_COLUMNS,
    "market_cap",
    "market_cap_currency",
    "adjusted_open",
    "raw_volume",
    "shares_outstanding",
    "shares_outstanding_source",
    "shares_outstanding_staleness_days",
)

WORLD_MARKET_SOURCE_COLUMNS = (
    "source",
    "series_id",
    "observation_time",
    "value",
    "available_at",
    "asof_known_at",
    "is_revision_prone",
    "is_final",
    "source_local_date",
)

CURRENT_TAXONOMY_SOURCE_COLUMNS = (
    *IDENTITY_COLUMNS,
    "ibkr_industry",
    "ibkr_category",
    "ibkr_subcategory",
)

CURRENT_TAXONOMY_BACKCAST_LABEL_COLUMNS = (
    "ibkr_taxbc_industry",
    "ibkr_taxbc_category",
    "ibkr_taxbc_subcategory",
)

CURRENT_TAXONOMY_BACKCAST_LEVEL_SPECS = (
    ("industry", ("ibkr_industry",)),
    ("category", ("ibkr_industry", "ibkr_category")),
    (
        "subcategory",
        ("ibkr_industry", "ibkr_category", "ibkr_subcategory"),
    ),
)

CURRENT_TAXONOMY_BACKCAST_METRIC_SUFFIXES = (
    "group_member_count",
    "group_median_return_21d_pct",
    "group_median_return_63d_pct",
    "group_median_return_126d_pct",
    "group_median_return_252d_pct",
    "group_return_21d_pct_rank",
    "group_return_63d_pct_rank",
    "group_return_126d_pct_rank",
    "group_return_252d_pct_rank",
    "group_rs_raw_median",
    "group_rs_raw_pct_rank",
    "stock_rs_raw_pct_rank",
    "above_ma50_ratio",
    "above_ma200_ratio",
    "above_ma50_ratio_change_5d",
    "above_ma50_ratio_change_21d",
    "above_ma200_ratio_change_5d",
    "above_ma200_ratio_change_21d",
    "new_52w_high_count",
    "new_52w_high_ratio",
    "new_52w_high_ratio_change_5d",
    "new_52w_high_ratio_change_21d",
    "rs70_ratio",
    "rs90_ratio",
    "trend_template_ratio",
    "leadership_breadth_score",
    "leadership_breadth_score_change_5d",
    "leadership_breadth_score_change_21d",
    "new_8of8_signal_count",
    "new_8of8_signal_ratio",
)

CURRENT_TAXONOMY_BACKCAST_FEATURE_COLUMNS = tuple(
    f"ibkr_taxbc_{level}_{suffix}"
    for level, _label_columns in CURRENT_TAXONOMY_BACKCAST_LEVEL_SPECS
    for suffix in CURRENT_TAXONOMY_BACKCAST_METRIC_SUFFIXES
)

CURRENT_TAXONOMY_BACKCAST_INTEGER_COLUMNS = tuple(
    f"ibkr_taxbc_{level}_{suffix}"
    for level, _label_columns in CURRENT_TAXONOMY_BACKCAST_LEVEL_SPECS
    for suffix in (
        "group_member_count",
        "new_52w_high_count",
        "new_8of8_signal_count",
    )
)

CURRENT_TAXONOMY_BACKCAST_UNIT_INTERVAL_COLUMNS = tuple(
    f"ibkr_taxbc_{level}_{suffix}"
    for level, _label_columns in CURRENT_TAXONOMY_BACKCAST_LEVEL_SPECS
    for suffix in CURRENT_TAXONOMY_BACKCAST_METRIC_SUFFIXES
    if suffix.endswith("_ratio")
    or suffix.endswith("_pct_rank")
    or suffix == "leadership_breadth_score"
)

CURRENT_TAXONOMY_BACKCAST_CHANGE_COLUMNS = tuple(
    f"ibkr_taxbc_{level}_{suffix}"
    for level, _label_columns in CURRENT_TAXONOMY_BACKCAST_LEVEL_SPECS
    for suffix in CURRENT_TAXONOMY_BACKCAST_METRIC_SUFFIXES
    if "_change_" in suffix
)

CURRENT_TAXONOMY_BACKCAST_GROUP_CONTEXT_COLUMNS = (
    "market_date",
    "taxonomy_level",
    "ibkr_industry",
    "ibkr_category",
    "ibkr_subcategory",
    "group_member_count",
    "return_21d_eligible_count",
    "group_median_return_21d_pct",
    "return_63d_eligible_count",
    "group_median_return_63d_pct",
    "return_126d_eligible_count",
    "group_median_return_126d_pct",
    "return_252d_eligible_count",
    "group_median_return_252d_pct",
    "rs_raw_eligible_count",
    "group_rs_raw_median",
    "ma50_eligible_count",
    "above_ma50_ratio",
    "ma200_eligible_count",
    "above_ma200_ratio",
    "new_52w_high_eligible_count",
    "new_52w_high_count",
    "new_52w_high_ratio",
    "rs_rating_eligible_count",
    "rs70_ratio",
    "rs90_ratio",
    "trend_template_eligible_count",
    "trend_template_ratio",
    "new_8of8_signal_count",
    "new_8of8_signal_ratio",
)

CURRENT_TAXONOMY_BACKCAST_MEMBER_RANK_COLUMNS = (
    "signal_date",
    *IDENTITY_COLUMNS,
    *(
        f"ibkr_taxbc_{level}_stock_rs_raw_pct_rank"
        for level, _label_columns in CURRENT_TAXONOMY_BACKCAST_LEVEL_SPECS
    ),
)

TECHNICAL_V3_FEATURE_COLUMNS = (
    "prior_adjusted_close",
    "prior_return_42d_pct",
    "prior_return_63d_pct",
    "prior_return_126d_pct",
    "prior_return_252d_pct",
    "prior_return_acceleration_21d_pct_points",
    "prior_daily_return_std_21d_pct",
    "prior_daily_return_std_63d_pct",
    "prior_downside_return_std_21d_pct",
    "prior_max_drawdown_63d_pct",
    "prior_max_drawdown_126d_pct",
    "prior_atr_5d_pct",
    "prior_atr_21d_pct",
    "prior_atr_5_vs21_ratio",
    "prior_atr_10_vs21_ratio",
    "prior_close_vs_126d_high_pct",
    "prior_close_vs_252d_high_pct",
    "prior_volume_sma5_vs50_ratio",
    "prior_volume_sma10_vs50_ratio",
    "prior_volume_sma21_vs50_ratio",
    "prior_notional_sma5_vs50_ratio",
    "prior_notional_sma10_vs50_ratio",
    "prior_notional_sma21_vs50_ratio",
    "prior_up_down_volume_ratio21",
    "prior_up_down_notional_ratio21",
    "prior_volume_dryup_share10",
    "prior_volume_dryup_share20",
    "prior_obv_slope_20",
    "prior_accumulation_day_count_20",
    "prior_high_volume_down_day_count_20",
    "prior_base_width_10_pct",
    "prior_base_width_40_pct",
    "prior_base_width_63_pct",
    "prior_tight_close_range_5_pct",
    "prior_tight_close_range_10_pct",
    "prior_tight_close_range_15_pct",
    "prior_range_compression_5_vs20_ratio",
    "ma50_slope_21d_pct",
    "ma150_slope_21d_pct",
    "ma200_slope_63d_pct",
    "prior_overhead_supply_share63",
    "prior_high_test_count_20",
    "prior_high_slope_20_pct_per_session",
    "prior_low_slope_20_pct_per_session",
    "prior_contraction_count_40",
    "prior_return_efficiency_63",
    "prior_rs_rating_change_21d",
    "prior_history_sessions",
    "signal_undercut_reclaim_10",
    "signal_volume_vs_prior_10d_max_down_volume_ratio",
)

# Continuous, causal chart-pattern proxies.  Every score is bounded to
# [0, 100].  The windowed score uses only sessions t-window through t-1 plus
# the already-known signal-day bar for the trigger component.  The separate
# setup/trigger columns use the canonical window declared below so research
# can distinguish a good base from a good entry bar.
SOFT_PATTERN_SPECS = (
    ("flat_base", (10, 15, 20, 30, 40, 63), 20),
    ("ordered_uptrend", (10, 15, 20, 30, 40, 63), 20),
    ("pullback", (10, 15, 20, 30, 40, 63), 40),
    ("v_recovery", (20, 30, 40, 63, 126), 40),
    ("volume_dryup_breakout", (10, 15, 20, 30, 40, 63), 20),
    ("distribution_top", (10, 15, 20, 30, 40, 63), 20),
    ("vcp", (20, 30, 40, 63, 126), 40),
    ("cup_with_handle", (63, 126), 126),
    ("high_tight_flag", (20, 30, 40, 63), 40),
)

# These patterns contain explicit activity contraction, breakout, distribution
# or handle-volume components.  The classic score keeps split-adjusted share
# volume; the parallel diagnostic score substitutes USD notional activity so
# research can measure the incremental capital-flow signal independently.
NOTIONAL_SOFT_PATTERN_BASE_NAMES = (
    "pullback",
    "volume_dryup_breakout",
    "distribution_top",
    "vcp",
    "cup_with_handle",
    "high_tight_flag",
)

NOTIONAL_SOFT_PATTERN_SPECS = tuple(
    (f"{pattern_name}_notional", windows, canonical_window)
    for pattern_name, windows, canonical_window in SOFT_PATTERN_SPECS
    if pattern_name in NOTIONAL_SOFT_PATTERN_BASE_NAMES
)

SOFT_PATTERN_FEATURE_COLUMNS = tuple(
    column
    for pattern_name, windows, _canonical_window in (
        *SOFT_PATTERN_SPECS,
        *NOTIONAL_SOFT_PATTERN_SPECS,
    )
    for column in (
        f"pattern_{pattern_name}_setup_score",
        f"pattern_{pattern_name}_trigger_score",
        *(f"pattern_{pattern_name}_score_{window}d" for window in windows),
    )
)

SUPPLY_DEMAND_FEATURE_COLUMNS = (
    "signal_adjusted_open",
    "signal_gap_pct",
    "signal_intraday_return_pct",
    "shares_outstanding",
    "log_shares_outstanding",
    "signal_turnover_ratio",
)

FUNDAMENTAL_FEATURE_COLUMNS = (
    "fundamental_snapshot_age_days",
    "fundamental_report_age_days",
    "fundamental_gross_margin_ttm_ratio",
    "fundamental_operating_margin_ttm_ratio",
    "fundamental_net_margin_ttm_ratio",
    "fundamental_fcf_margin_ttm_ratio",
    "fundamental_fcf_sbc_adjusted_margin_ttm_ratio",
    "fundamental_debt_to_capital_ratio",
    "fundamental_cash_to_assets_ratio",
    "fundamental_current_ratio",
    "fundamental_accruals_ratio",
    "fundamental_sbc_to_revenue_ttm_ratio",
    "fundamental_operating_cashflow_margin_ttm_ratio",
    "fundamental_operating_cashflow_ttm_yoy_change_ratio",
    "fundamental_fcf_ttm_yoy_change_ratio",
    "fundamental_fcf_sbc_adjusted_ttm_yoy_change_ratio",
    "fundamental_operating_cashflow_ttm_sequential_change_ratio",
    "fundamental_fcf_ttm_sequential_change_ratio",
    "fundamental_fcf_sbc_adjusted_ttm_sequential_change_ratio",
    "fundamental_operating_cashflow_margin_ttm_yoy_change",
    "fundamental_fcf_margin_ttm_yoy_change",
    "fundamental_fcf_sbc_adjusted_margin_ttm_yoy_change",
    "fundamental_operating_cashflow_ttm_growth_acceleration",
    "fundamental_fcf_ttm_growth_acceleration",
    "fundamental_fcf_sbc_adjusted_ttm_growth_acceleration",
    "fundamental_operating_cashflow_ttm_yoy_negative_to_positive",
    "fundamental_fcf_ttm_yoy_negative_to_positive",
    "fundamental_fcf_sbc_adjusted_ttm_yoy_negative_to_positive",
    "fundamental_rd_to_revenue_ttm_ratio",
    "fundamental_sga_to_revenue_ttm_ratio",
    "fundamental_capex_to_revenue_ttm_ratio",
    "fundamental_da_to_revenue_ttm_ratio",
    "fundamental_roe_ttm_ratio",
    "fundamental_roa_ttm_ratio",
    "fundamental_cash_conversion_ttm_ratio",
    "fundamental_fcf_conversion_ttm_ratio",
    "fundamental_fcf_sbc_adjusted_conversion_ttm_ratio",
    "fundamental_interest_coverage_ttm_ratio",
    "fundamental_debt_to_assets_ratio",
    "fundamental_net_debt_to_assets_ratio",
    "fundamental_debt_to_operating_income_ttm_ratio",
    "fundamental_net_debt_to_fcf_ttm_ratio",
    "fundamental_quick_ratio",
    "fundamental_working_capital_to_assets_ratio",
    "fundamental_goodwill_intangibles_to_assets_ratio",
    "fundamental_inventory_to_revenue_ttm_ratio",
    "fundamental_receivables_to_revenue_ttm_ratio",
    "fundamental_payables_to_revenue_ttm_ratio",
    "fundamental_asset_turnover_ttm_ratio",
    "fundamental_diluted_share_pressure_ratio",
    "fundamental_buyback_to_revenue_ttm_ratio",
    "fundamental_sec_shares_change_1y_ratio",
    "fundamental_quarter_filing_age_days",
    "fundamental_quarter_age_days",
    "fundamental_quarterly_revenue_yoy_growth_ratio",
    "fundamental_quarterly_eps_yoy_change_ratio",
    "fundamental_quarterly_eps_yoy_growth_ratio",
    "fundamental_quarterly_loss_to_profit",
    "fundamental_quarterly_revenue_growth_acceleration",
    "fundamental_quarterly_eps_growth_acceleration",
    "fundamental_quarterly_revenue_sequential_growth_ratio",
    "fundamental_quarterly_eps_sequential_change_ratio",
    "fundamental_revenue_growth_streak_4q",
    "fundamental_eps_growth_streak_4q",
    "fundamental_quarterly_operating_margin_ratio",
    "fundamental_quarterly_operating_margin_yoy_change",
    "fundamental_quarterly_net_margin_ratio",
    "fundamental_quarterly_net_margin_yoy_change",
    "fundamental_quarterly_operating_margin_acceleration",
    "fundamental_quarterly_net_margin_acceleration",
)

EARNINGS_EVENT_FEATURE_COLUMNS = (
    "earnings_event_age_days",
    "earnings_event_on_signal_day",
    "earnings_event_within_5d",
    "earnings_event_within_21d",
)

GLOBAL_MARKET_FEATURE_COLUMNS = (
    "cross_sectional_rs_21d_pct_rank",
    "cross_sectional_rs_63d_pct_rank",
    "cross_sectional_rs_126d_pct_rank",
    "cross_sectional_rs_252d_pct_rank",
    "market_breadth_above_ma50_ratio",
    "market_breadth_above_ma150_ratio",
    "market_breadth_above_ma200_ratio",
    "market_breadth_trend_template_ratio",
    "market_breadth_rs70_ratio",
    "market_breadth_rs90_ratio",
    "market_advancer_ratio",
    "market_median_daily_return_pct",
    "market_breadth_above_ma50_change_5d",
    "market_breadth_above_ma200_change_21d",
    "market_spy_prior_return_5d_pct",
    "market_spy_prior_return_21d_pct",
    "market_spy_prior_return_63d_pct",
    "market_qqq_prior_return_5d_pct",
    "market_qqq_prior_return_21d_pct",
    "market_qqq_prior_return_63d_pct",
    "market_iwm_prior_return_5d_pct",
    "market_iwm_prior_return_21d_pct",
    "market_iwm_prior_return_63d_pct",
    "market_dia_prior_return_21d_pct",
    "relative_return_vs_spy_21d_pct_points",
    "relative_return_vs_spy_63d_pct_points",
    "relative_return_vs_qqq_21d_pct_points",
    "relative_return_vs_qqq_63d_pct_points",
    "relative_return_vs_iwm_21d_pct_points",
    "relative_return_vs_iwm_63d_pct_points",
    "market_vix_level",
    "market_vxn_level",
    "market_vvix_level",
    "market_skew_level",
    "market_vix9d_to_vix_ratio",
    "market_vix_to_vix3m_ratio",
)

EARLY_GLOBAL_MARKET_FEATURE_COLUMNS = (
    "market_breadth_above_ma50_ratio",
    "market_breadth_above_ma200_ratio",
    "market_breadth_trend_template_ratio",
    "market_advancer_ratio",
    "market_median_daily_return_pct",
    "market_spy_prior_return_5d_pct",
    "market_qqq_prior_return_5d_pct",
    "market_iwm_prior_return_5d_pct",
    "market_vix_level",
    "market_vxn_level",
    "market_vix9d_to_vix_ratio",
    "market_vix_to_vix3m_ratio",
    "market_spy_return_since_signal_pct",
    "market_qqq_return_since_signal_pct",
    "market_iwm_return_since_signal_pct",
    "relative_return_vs_spy_since_signal_pct_points",
    "relative_return_vs_qqq_since_signal_pct_points",
    "relative_return_vs_iwm_since_signal_pct_points",
)

EARLY_CONFIRMATION_RELATIVE_FEATURE_COLUMNS = (
    "cross_sectional_close_return_since_signal_pct_rank",
    "cross_sectional_relative_return_vs_spy_since_signal_pct_rank",
    "early_relative_strength_score",
)

EARLY_CONFIRMATION_PATH_FEATURE_COLUMNS = (
    "signal_adjusted_open",
    "signal_adjusted_high",
    "signal_adjusted_low",
    "signal_prior_adjusted_close",
    "signal_gap_pct",
    "close_vs_signal_high_pct",
    "signal_day_move_retention_ratio",
    "closes_above_signal_high_share_since_signal",
    "closes_above_signal_close_share_since_signal",
    "higher_high_share_since_signal",
    "higher_low_share_since_signal",
    "mean_close_location_since_signal",
    "path_efficiency_since_signal",
    "mfe_retention_ratio",
    "close_return_from_signal_atr_units",
    "max_gain_to_landmark_atr_units",
    "max_loss_to_landmark_atr_units",
    "drawdown_from_post_signal_high_atr_units",
    "up_volume_share_since_signal",
    "up_notional_share_since_signal",
    "pullback_volume_vs_advance_volume_ratio_since_signal",
    "pullback_notional_vs_advance_notional_ratio_since_signal",
    "breakout_acceptance_score",
    "early_path_quality_score",
)

EARLY_CONFIRMATION_SIGNAL_FEATURE_COLUMNS = (
    "signal_daily_price_change_pct",
    "signal_volume_vs_sma21_prior_ratio",
    "signal_notional_vs_sma21_prior_ratio",
    "signal_close_location_value",
    "signal_close_vs_prior_20d_high_pct",
    "signal_prior_range_compression_10_vs_10_ratio",
    "signal_prior_atr_14d_pct",
    "signal_prior_base_width_20_pct",
    "signal_prior_volume_sma5_vs21_ratio",
    "signal_prior_notional_sma5_vs21_ratio",
    "signal_volume_dryup_breakout_score_20d",
    "signal_volume_dryup_breakout_notional_score_20d",
)

MARKET_CAP_FEATURE_COLUMNS = (
    "market_cap_usd",
    "log_market_cap_usd",
    "market_cap_shares_staleness_days",
)

SIGNAL_COLUMNS = (
    "signal_date",
    "previous_session_date",
    *IDENTITY_COLUMNS,
    "price_continuity_segment",
    "currency",
    "raw_close",
    "adjusted_close",
    "adjusted_high",
    "adjusted_low",
    "adjusted_volume",
    "daily_price_change_pct",
    "adjusted_volume_sma21_prior",
    "adjusted_volume_vs_sma21_prior_ratio",
    "adjusted_volume_vs_sma7_prior_ratio",
    "adjusted_volume_vs_sma14_prior_ratio",
    "adjusted_volume_sma50_prior",
    "adjusted_volume_vs_sma50_prior_ratio",
    "adjusted_volume_vs_sma100_prior_ratio",
    "daily_traded_notional_usd",
    "daily_traded_notional_sma21_prior_usd",
    "daily_traded_notional_vs_sma21_prior_ratio",
    "daily_traded_notional_vs_sma7_prior_ratio",
    "daily_traded_notional_vs_sma14_prior_ratio",
    "daily_traded_notional_sma50_prior_usd",
    "daily_traded_notional_vs_sma50_prior_ratio",
    "daily_traded_notional_vs_sma100_prior_ratio",
    "dollar_volume_63d",
    *SHORT_MA_SOURCE_COLUMNS,
    "ma50",
    "ma150",
    "ma200",
    "ma200_21_sessions_ago",
    "low_52w",
    "high_52w",
    "close_vs_prior_26w_high_pct",
    *CANDLE_BODY_SOURCE_COLUMNS,
    "rs_raw",
    "rs_rating",
    "rs_universe_size",
    *SHORT_TERM_DERIVED_FEATURE_COLUMNS,
    "trigger_criteria",
    "trigger_count",
    "previous_criteria_pass_count",
    "prior_7_of_8_count_10d",
    "sessions_since_previous_pass",
    "distance_to_ma50_pct",
    "distance_to_ma150_pct",
    "distance_to_ma200_pct",
    "ma50_vs_ma150_pct",
    "ma50_vs_ma200_pct",
    "ma150_vs_ma200_pct",
    "ma200_slope_21d_pct",
    "price_vs_52w_low_pct",
    "price_vs_52w_high_pct",
    "prior_return_5d_pct",
    "prior_return_10d_pct",
    "prior_return_21d_pct",
    "prior_momentum_acceleration_5d_pct_points",
    "prior_atr_14d_pct",
    "prior_max_drawdown_21d_pct",
    "prior_close_vs_20d_high_pct",
    "prior_close_vs_63d_high_pct",
    "signal_close_vs_prior_20d_high_pct",
    "prior_range_compression_10_vs_10_ratio",
    "signal_close_location_value",
    "prior_rs_rating_change_5d",
    "prior_volume_sma5_vs21_ratio",
    "prior_volume_sma10_vs21_ratio",
    "prior_notional_sma5_vs21_ratio",
    "prior_notional_sma10_vs21_ratio",
    "prior_up_volume_share21",
    "prior_up_notional_share21",
    "prior_price_volume_corr21",
    "prior_price_notional_corr21",
    "prior_base_width_20_pct",
    "prior_trend_slope_20_pct_per_session",
    "prior_trend_r2_20",
    "prior_trend_efficiency_20",
    "prior_positive_return_share_20",
    "prior_peak_age_40_sessions",
    "prior_pullback_from_40d_high_pct",
    "prior_trough_age_40_sessions",
    "prior_drawdown_to_trough_40_pct",
    "prior_recovery_from_trough_40_pct",
    "prior_v_recovery_fraction_40",
    "prior_distribution_day_count_20",
    "prior_churning_day_count_20",
    "prior_failed_breakout_count_20",
    *TECHNICAL_V3_FEATURE_COLUMNS,
    *SOFT_PATTERN_FEATURE_COLUMNS,
    *FUNDAMENTAL_FEATURE_COLUMNS,
    *EARNINGS_EVENT_FEATURE_COLUMNS,
    *MARKET_CAP_FEATURE_COLUMNS,
    *SUPPLY_DEMAND_FEATURE_COLUMNS,
    *GLOBAL_MARKET_FEATURE_COLUMNS,
    *CURRENT_TAXONOMY_BACKCAST_LABEL_COLUMNS,
    *CURRENT_TAXONOMY_BACKCAST_FEATURE_COLUMNS,
    "forward_5d_max_gain_pct",
    "forward_5d_max_loss_pct",
    "forward_10d_max_gain_pct",
    "forward_10d_max_loss_pct",
    "forward_20d_max_gain_pct",
    "forward_20d_max_loss_pct",
    "forward_30d_max_gain_pct",
    "forward_30d_max_loss_pct",
    "forward_40d_max_gain_pct",
    "forward_40d_max_loss_pct",
    "forward_60d_max_gain_pct",
    "forward_60d_max_loss_pct",
    "forward_90d_max_gain_pct",
    "forward_90d_max_loss_pct",
    "forward_5d_label_end_date",
    "forward_10d_label_end_date",
    "forward_20d_label_end_date",
    "forward_30d_label_end_date",
    "forward_40d_label_end_date",
    "forward_60d_label_end_date",
    "forward_90d_label_end_date",
    "terminal_close_return_5d_pct",
    "terminal_close_return_10d_pct",
    "terminal_close_return_20d_pct",
    "terminal_close_return_30d_pct",
    "terminal_close_return_40d_pct",
    "terminal_close_return_60d_pct",
    "terminal_close_return_90d_pct",
    "first_gain_2pct_day",
    "first_gain_1pct_day",
    "first_gain_3pct_day",
    "first_gain_5pct_day",
    "first_loss_5pct_day",
    "first_loss_10pct_day",
    "gain_loss_order_5d",
    "weak_5d",
    "strong_5d",
    "deep_loss_5d",
    "bad_5d",
    "loss_first_5d",
    "strong_first_5d",
    "terminal_stagnant_5d",
    "terminal_winner_5d",
    "stagnant_5d",
    "hard_stop_10pct_5d",
    "terminal_nonpositive_20d",
    "terminal_winner_20d",
    "terminal_nonpositive_30d",
    "terminal_winner_30d",
    "runner_60d",
    "runner_90d",
    "mfe_to_abs_mae_5d_ratio",
    "terminal_return_to_mfe_5d_ratio",
    "late_strong_10d",
    "late_strong_20d",
    "analysis_split",
    "include_weak_filter",
    "include_loss_first_filter",
    "include_final",
    "strong_confirmation",
    "weak_matched_rule_ids",
    "loss_first_matched_rule_ids",
    "matched_rule_ids",
    "confirmation_matched_rule_ids",
    "confirmation_reason",
    "filter_decision",
    "exclusion_reason",
)

EARLY_CUT_COLUMNS = (
    "signal_date",
    "landmark_day",
    "landmark_date",
    "effective_session_date",
    "horizon_end_date",
    "day20_end_date",
    "day40_end_date",
    "day60_end_date",
    "day90_end_date",
    *IDENTITY_COLUMNS,
    "price_continuity_segment",
    "currency",
    "decision_stage",
    "landmark_observed",
    "same_continuity_segment",
    "eligible_at_landmark",
    "early_confirmation_eligible_at_landmark",
    "active_at_landmark",
    "prior_policy_cut_day",
    "full_outcome_available",
    "early_confirmation_outcome_available",
    "signal_adjusted_close",
    "landmark_adjusted_close",
    "landmark_adjusted_high",
    "landmark_adjusted_low",
    "landmark_adjusted_volume",
    "landmark_daily_traded_notional_usd",
    "landmark_daily_price_change_pct",
    "landmark_volume_vs_sma21_prior_ratio",
    "landmark_volume_vs_sma50_prior_ratio",
    "landmark_notional_vs_sma21_prior_ratio",
    "landmark_notional_vs_sma50_prior_ratio",
    "landmark_volume_vs_sma7_prior_ratio",
    "landmark_volume_vs_sma14_prior_ratio",
    "landmark_volume_vs_sma100_prior_ratio",
    "landmark_notional_vs_sma7_prior_ratio",
    "landmark_notional_vs_sma14_prior_ratio",
    "landmark_notional_vs_sma100_prior_ratio",
    "landmark_rs_rating",
    "landmark_criteria_pass_count",
    "landmark_trend_template_pass",
    "close_return_from_signal_pct",
    "max_gain_to_landmark_pct",
    "max_loss_to_landmark_pct",
    "drawdown_from_post_signal_high_pct",
    "rebound_from_post_signal_low_pct",
    "landmark_true_range_pct",
    "landmark_close_location_value",
    "volume_vs_signal_ratio",
    "notional_vs_signal_ratio",
    "rs_rating_change_from_signal",
    "landmark_distance_to_ma50_pct",
    "landmark_distance_to_ma150_pct",
    "landmark_distance_to_ma200_pct",
    "landmark_price_vs_52w_high_pct",
    "landmark_atr_14d_pct",
    "landmark_return_5d_pct",
    "landmark_return_10d_pct",
    "landmark_return_20d_pct",
    "landmark_max_drawdown_20d_pct",
    "landmark_trend_slope_20_pct_per_session",
    "landmark_trend_r2_20",
    "landmark_trend_efficiency_20",
    "landmark_range_compression_10_vs_10_ratio",
    "landmark_distribution_day_count_20",
    "landmark_churning_day_count_20",
    "mean_volume_since_signal_vs_prior21_ratio",
    "mean_notional_since_signal_vs_prior21_ratio",
    *EARLY_CONFIRMATION_PATH_FEATURE_COLUMNS,
    *EARLY_CONFIRMATION_SIGNAL_FEATURE_COLUMNS,
    "hit_gain_2pct_so_far",
    "hit_gain_5pct_so_far",
    "hit_loss_5pct_so_far",
    "hit_loss_10pct_so_far",
    "first_gain_2pct_day_so_far",
    "first_gain_5pct_day_so_far",
    "first_loss_5pct_day_so_far",
    "first_loss_10pct_day_so_far",
    "remaining_max_gain_from_signal_pct",
    "remaining_max_loss_from_signal_pct",
    "remaining_max_gain_from_landmark_pct",
    "remaining_max_loss_from_landmark_pct",
    "terminal_close_return_from_signal_pct",
    "terminal_close_return_from_landmark_pct",
    "future_first_gain_2pct_day",
    "future_first_gain_5pct_day",
    "future_first_loss_5pct_day",
    "continuation_outcome",
    "stagnant_to_day5",
    "loss_first_to_day5",
    "strong_first_to_day5",
    "bad_to_day5",
    "early_first_gain_5pct_day_to_day20",
    "early_first_loss_5pct_day_to_day20",
    "early_gain_loss_order_to_day20",
    "early_strong_first_to_day20",
    "early_loss_first_to_day20",
    "early_winner_to_day20",
    "early_bad_to_day20",
    "stagnant_at_day5",
    "effective_adjusted_open",
    "effective_open_return_from_signal_pct",
    "max_gain_from_effective_open_to_day20_pct",
    "max_loss_from_effective_open_to_day20_pct",
    "terminal_return_from_effective_open_to_day20_pct",
    "take_profit_better_to_day20",
    "continue_winner_to_day20",
    "max_gain_from_effective_open_to_day40_pct",
    "max_loss_from_effective_open_to_day40_pct",
    "terminal_return_from_effective_open_to_day40_pct",
    "take_profit_better_to_day40",
    "continue_winner_to_day40",
    "max_gain_from_effective_open_to_day60_pct",
    "max_loss_from_effective_open_to_day60_pct",
    "terminal_return_from_effective_open_to_day60_pct",
    "take_profit_better_to_day60",
    "continue_winner_to_day60",
    "max_gain_from_effective_open_to_day90_pct",
    "max_loss_from_effective_open_to_day90_pct",
    "terminal_return_from_effective_open_to_day90_pct",
    "take_profit_better_to_day90",
    "continue_winner_to_day90",
    *EARLY_GLOBAL_MARKET_FEATURE_COLUMNS,
    *EARLY_CONFIRMATION_RELATIVE_FEATURE_COLUMNS,
    "analysis_split",
    "include_stagnation_filter",
    "include_loss_filter",
    "include_final",
    "stagnation_matched_rule_ids",
    "loss_matched_rule_ids",
    "matched_rule_ids",
    "cut_decision",
    "cut_reason",
    "early_confirmation_include_final",
    "early_confirmation_matched_rule_ids",
    "early_confirmation_decision",
    "early_confirmation_reason",
    "management_include_final",
    "management_matched_rule_ids",
    "management_decision",
    "management_reason",
)

RULE_COLUMNS = (
    "rule_id",
    "result_kind",
    "decision_family",
    "objective",
    "protected_outcome",
    "landmark_day",
    "feature_group",
    "feature_name",
    "operator",
    "quantile_value",
    "threshold_value",
    "rule_text",
    "pattern_name",
    "pattern_match_mode",
    "pattern_total_clause_count",
    "pattern_required_clause_count",
    "pattern_score_window_sessions",
    "pattern_score_threshold_pct",
    "selection_order",
    "evaluation_scope",
    "scope_year",
    "period_start",
    "period_end",
    "threshold_fit_end_date",
    "is_selected",
    "is_final_filter",
    "passes_holdout",
    "passes_development_gates",
    "passes_stability_gates",
    "passes_multiple_testing",
    "multiple_testing_candidate_count",
    "permutation_trial_count",
    "max_stat_permutation_p_value",
    "component_count",
    "population_count",
    "sample_count",
    "unlabeled_count",
    "matched_count",
    "matched_labeled_count",
    "matched_unlabeled_count",
    "objective_count",
    "protected_count",
    "matched_objective_count",
    "matched_protected_count",
    "label_coverage_rate",
    "matched_label_coverage_rate",
    "match_rate",
    "population_objective_rate",
    "matched_objective_rate",
    "objective_capture_rate",
    "objective_lift",
    "protected_rejection_rate",
    "protected_retention_rate",
    "retained_objective_rate",
    "retained_protected_rate",
    "eligible_fold_count",
    "positive_lift_fold_count",
    "positive_lift_fold_fraction",
    "median_fold_objective_lift",
    "min_fold_objective_lift",
    "min_fold_protected_retention_rate",
    "max_fold_match_rate",
    "selection_score",
)

ENTRY_FEATURE_GROUPS = {
    "A": (
        "adjusted_volume_vs_sma21_prior_ratio",
        "adjusted_volume_vs_sma7_prior_ratio",
        "adjusted_volume_vs_sma14_prior_ratio",
        "adjusted_volume_vs_sma50_prior_ratio",
        "adjusted_volume_vs_sma100_prior_ratio",
        "daily_traded_notional_vs_sma21_prior_ratio",
        "daily_traded_notional_vs_sma7_prior_ratio",
        "daily_traded_notional_vs_sma14_prior_ratio",
        "daily_traded_notional_vs_sma50_prior_ratio",
        "daily_traded_notional_vs_sma100_prior_ratio",
        "daily_traded_notional_usd",
        "daily_price_change_pct",
        "dollar_volume_63d",
        "rs_rating",
        "trigger_count",
        "previous_criteria_pass_count",
        "prior_7_of_8_count_10d",
        "sessions_since_previous_pass",
        "distance_to_ma50_pct",
        "distance_to_ma150_pct",
        "distance_to_ma200_pct",
        "ma50_vs_ma150_pct",
        "ma50_vs_ma200_pct",
        "ma150_vs_ma200_pct",
        "ma200_slope_21d_pct",
        "price_vs_52w_low_pct",
        "price_vs_52w_high_pct",
        "signal_close_vs_prior_20d_high_pct",
        "signal_close_location_value",
    ),
    "B": (
        "prior_return_5d_pct",
        "prior_return_10d_pct",
        "prior_return_21d_pct",
        "prior_momentum_acceleration_5d_pct_points",
        "prior_atr_14d_pct",
        "prior_max_drawdown_21d_pct",
        "prior_close_vs_20d_high_pct",
        "prior_close_vs_63d_high_pct",
        "prior_range_compression_10_vs_10_ratio",
        "prior_rs_rating_change_5d",
    ),
    "C": (
        "prior_volume_sma5_vs21_ratio",
        "prior_volume_sma10_vs21_ratio",
        "prior_notional_sma5_vs21_ratio",
        "prior_notional_sma10_vs21_ratio",
        "prior_up_volume_share21",
        "prior_up_notional_share21",
        "prior_price_volume_corr21",
        "prior_price_notional_corr21",
    ),
    "D": (
        "prior_base_width_20_pct",
        "prior_trend_slope_20_pct_per_session",
        "prior_trend_r2_20",
        "prior_trend_efficiency_20",
        "prior_positive_return_share_20",
        "prior_peak_age_40_sessions",
        "prior_pullback_from_40d_high_pct",
        "prior_trough_age_40_sessions",
        "prior_drawdown_to_trough_40_pct",
        "prior_recovery_from_trough_40_pct",
        "prior_v_recovery_fraction_40",
        "prior_distribution_day_count_20",
        "prior_churning_day_count_20",
        "prior_failed_breakout_count_20",
    ),
    "K": SHORT_TERM_STRUCTURE_FEATURE_COLUMNS,
    "T": TECHNICAL_V3_FEATURE_COLUMNS,
    "P": SOFT_PATTERN_FEATURE_COLUMNS,
    "S": SUPPLY_DEMAND_FEATURE_COLUMNS,
    "F": FUNDAMENTAL_FEATURE_COLUMNS,
    "N": EARNINGS_EVENT_FEATURE_COLUMNS,
    "R": GLOBAL_MARKET_FEATURE_COLUMNS,
    # Raw market cap is retained for fixed absolute-range interactions. Its log
    # transform is the non-redundant atomic size feature used for quantiles.
    "M": (
        "log_market_cap_usd",
        "market_cap_shares_staleness_days",
    ),
}

EARLY_CUT_FEATURE_GROUPS = {
    "E": (
        "close_return_from_signal_pct",
        "max_gain_to_landmark_pct",
        "max_loss_to_landmark_pct",
        "drawdown_from_post_signal_high_pct",
        "rebound_from_post_signal_low_pct",
        "landmark_daily_price_change_pct",
        "landmark_true_range_pct",
        "landmark_close_location_value",
        "landmark_volume_vs_sma21_prior_ratio",
        "landmark_volume_vs_sma7_prior_ratio",
        "landmark_volume_vs_sma14_prior_ratio",
        "landmark_volume_vs_sma50_prior_ratio",
        "landmark_volume_vs_sma100_prior_ratio",
        "landmark_notional_vs_sma21_prior_ratio",
        "landmark_notional_vs_sma7_prior_ratio",
        "landmark_notional_vs_sma14_prior_ratio",
        "landmark_notional_vs_sma50_prior_ratio",
        "landmark_notional_vs_sma100_prior_ratio",
        "volume_vs_signal_ratio",
        "notional_vs_signal_ratio",
        "rs_rating_change_from_signal",
        "landmark_distance_to_ma50_pct",
        "landmark_distance_to_ma150_pct",
        "landmark_distance_to_ma200_pct",
        "landmark_price_vs_52w_high_pct",
        "landmark_atr_14d_pct",
        "landmark_return_5d_pct",
        "landmark_return_10d_pct",
        "landmark_return_20d_pct",
        "landmark_max_drawdown_20d_pct",
        "landmark_trend_slope_20_pct_per_session",
        "landmark_trend_r2_20",
        "landmark_trend_efficiency_20",
        "landmark_range_compression_10_vs_10_ratio",
        "landmark_distribution_day_count_20",
        "landmark_churning_day_count_20",
        "mean_volume_since_signal_vs_prior21_ratio",
        "mean_notional_since_signal_vs_prior21_ratio",
        "landmark_criteria_pass_count",
    ),
    "R": EARLY_GLOBAL_MARKET_FEATURE_COLUMNS,
}

EARLY_CONFIRMATION_FEATURE_GROUPS = {
    "E": (
        *EARLY_CUT_FEATURE_GROUPS["E"],
        *EARLY_CONFIRMATION_PATH_FEATURE_COLUMNS,
        *EARLY_CONFIRMATION_SIGNAL_FEATURE_COLUMNS,
    ),
    "R": (
        *EARLY_GLOBAL_MARKET_FEATURE_COLUMNS,
        *EARLY_CONFIRMATION_RELATIVE_FEATURE_COLUMNS,
    ),
}

# Kept as the public entry-feature name used by the research module.
FEATURE_GROUPS = ENTRY_FEATURE_GROUPS

SOURCE_BOOLEAN_COLUMNS = (*CRITERION_COLUMNS, "trend_template_pass")
SOURCE_INTEGER_COLUMNS = (
    "cik",
    "price_continuity_segment",
    "adjusted_volume",
    "rs_rating",
    "rs_universe_size",
)

SIGNAL_BOOLEAN_COLUMNS = (
    "weak_5d",
    "strong_5d",
    "deep_loss_5d",
    "bad_5d",
    "loss_first_5d",
    "strong_first_5d",
    "terminal_stagnant_5d",
    "terminal_winner_5d",
    "stagnant_5d",
    "hard_stop_10pct_5d",
    "terminal_nonpositive_20d",
    "terminal_winner_20d",
    "terminal_nonpositive_30d",
    "terminal_winner_30d",
    "runner_60d",
    "runner_90d",
    "late_strong_10d",
    "late_strong_20d",
    "include_weak_filter",
    "include_loss_first_filter",
    "include_final",
    "strong_confirmation",
)
SIGNAL_INTEGER_COLUMNS = (
    "cik",
    "price_continuity_segment",
    "adjusted_volume",
    "rs_rating",
    "rs_universe_size",
    "trigger_count",
    "previous_criteria_pass_count",
    "prior_7_of_8_count_10d",
    "sessions_since_previous_pass",
    "prior_peak_age_40_sessions",
    "prior_trough_age_40_sessions",
    "prior_distribution_day_count_20",
    "prior_churning_day_count_20",
    "prior_failed_breakout_count_20",
    "market_cap_usd",
    "market_cap_shares_staleness_days",
    "shares_outstanding",
    "prior_history_sessions",
    "first_gain_2pct_day",
    "first_gain_1pct_day",
    "first_gain_3pct_day",
    "first_gain_5pct_day",
    "first_loss_5pct_day",
    "first_loss_10pct_day",
    *CURRENT_TAXONOMY_BACKCAST_INTEGER_COLUMNS,
)

EARLY_CUT_BOOLEAN_COLUMNS = (
    "landmark_observed",
    "same_continuity_segment",
    "eligible_at_landmark",
    "early_confirmation_eligible_at_landmark",
    "active_at_landmark",
    "full_outcome_available",
    "early_confirmation_outcome_available",
    "landmark_trend_template_pass",
    "hit_gain_2pct_so_far",
    "hit_gain_5pct_so_far",
    "hit_loss_5pct_so_far",
    "stagnant_to_day5",
    "loss_first_to_day5",
    "strong_first_to_day5",
    "bad_to_day5",
    "early_strong_first_to_day20",
    "early_loss_first_to_day20",
    "early_winner_to_day20",
    "early_bad_to_day20",
    "stagnant_at_day5",
    "hit_loss_10pct_so_far",
    "take_profit_better_to_day20",
    "continue_winner_to_day20",
    "take_profit_better_to_day40",
    "continue_winner_to_day40",
    "take_profit_better_to_day60",
    "continue_winner_to_day60",
    "take_profit_better_to_day90",
    "continue_winner_to_day90",
    "include_stagnation_filter",
    "include_loss_filter",
    "include_final",
    "early_confirmation_include_final",
    "management_include_final",
)
EARLY_CUT_INTEGER_COLUMNS = (
    "cik",
    "landmark_day",
    "prior_policy_cut_day",
    "price_continuity_segment",
    "landmark_adjusted_volume",
    "landmark_rs_rating",
    "landmark_criteria_pass_count",
    "first_gain_2pct_day_so_far",
    "first_gain_5pct_day_so_far",
    "first_loss_5pct_day_so_far",
    "first_loss_10pct_day_so_far",
    "future_first_gain_2pct_day",
    "future_first_gain_5pct_day",
    "future_first_loss_5pct_day",
    "early_first_gain_5pct_day_to_day20",
    "early_first_loss_5pct_day_to_day20",
)

RULE_BOOLEAN_COLUMNS = (
    "is_selected",
    "is_final_filter",
    "passes_holdout",
    "passes_development_gates",
    "passes_stability_gates",
    "passes_multiple_testing",
)
RULE_INTEGER_COLUMNS = (
    "landmark_day",
    "selection_order",
    "scope_year",
    "component_count",
    "pattern_total_clause_count",
    "pattern_required_clause_count",
    "pattern_score_window_sessions",
    "population_count",
    "sample_count",
    "unlabeled_count",
    "matched_count",
    "matched_labeled_count",
    "matched_unlabeled_count",
    "objective_count",
    "protected_count",
    "matched_objective_count",
    "matched_protected_count",
    "eligible_fold_count",
    "positive_lift_fold_count",
    "multiple_testing_candidate_count",
    "permutation_trial_count",
)
