from __future__ import annotations


IDENTITY_COLUMNS = ("symbol", "exchange", "cik")

ANALYSER_COLUMNS = (
    "period_end_date",
    *IDENTITY_COLUMNS,
    "price_continuity_segment",
    "currency",
    "raw_close",
    "adjusted_close",
    "adjusted_high",
    "adjusted_low",
    "adjusted_volume",
    "daily_price_change_pct",
    "adjusted_volume_sma21_prior",
    "adjusted_volume_vs_sma21_prior_ratio",
    "adjusted_volume_sma50_prior",
    "adjusted_volume_vs_sma50_prior_ratio",
    "daily_traded_notional_usd",
    "daily_traded_notional_sma21_prior_usd",
    "daily_traded_notional_vs_sma21_prior_ratio",
    "daily_traded_notional_sma50_prior_usd",
    "daily_traded_notional_vs_sma50_prior_ratio",
    "dollar_volume_63d",
    "ma5",
    "ma9",
    "ma21",
    "ma50",
    "ma150",
    "ma200",
    "ma200_21_sessions_ago",
    "low_52w",
    "high_52w",
    "rs_raw",
    "rs_rating",
    "rs_universe_size",
    "forward_5d_max_gain_pct",
    "forward_5d_max_loss_pct",
    "forward_10d_max_gain_pct",
    "forward_10d_max_loss_pct",
    "forward_15d_max_gain_pct",
    "forward_15d_max_loss_pct",
    "forward_20d_max_gain_pct",
    "forward_20d_max_loss_pct",
    "forward_30d_max_gain_pct",
    "forward_30d_max_loss_pct",
    "forward_45d_max_gain_pct",
    "forward_45d_max_loss_pct",
    "forward_60d_max_gain_pct",
    "forward_60d_max_loss_pct",
    "forward_90d_max_gain_pct",
    "forward_90d_max_loss_pct",
    "crit_price_above_ma150_200",
    "crit_ma150_above_ma200",
    "crit_ma200_rising",
    "crit_ma50_above_ma150_200",
    "crit_price_above_ma50",
    "crit_above_52w_low",
    "crit_near_52w_high",
    "crit_rs_rating",
    "trend_template_pass",
)

ANALYSER_PAYLOAD_COLUMNS = tuple(
    column
    for column in ANALYSER_COLUMNS
    if column not in {"period_end_date", *IDENTITY_COLUMNS}
)

ANALYSER_CRITERION_COLUMNS = (
    "crit_price_above_ma150_200",
    "crit_ma150_above_ma200",
    "crit_ma200_rising",
    "crit_ma50_above_ma150_200",
    "crit_price_above_ma50",
    "crit_above_52w_low",
    "crit_near_52w_high",
    "crit_rs_rating",
)

SOURCE_COLUMNS = (
    "period_end_date",
    *IDENTITY_COLUMNS,
    "last_update_ts",
    "adjusted_open",
    "adjusted_high",
    "adjusted_low",
    "adjusted_close",
    "price_continuity_segment",
    "price_continuity_break",
)

RUN_RESULT_COLUMNS = (
    "run_id",
    "started_at_utc",
    "completed_at_utc",
    "account_type",
    "currency",
    "trading_timezone",
    "requested_start_date",
    "actual_start_date",
    "end_date",
    "starting_capital_usd",
    "ending_cash_usd",
    "ending_market_value_usd",
    "ending_equity_usd",
    "realized_pnl_usd",
    "unrealized_pnl_usd",
    "total_return_pct",
    "max_drawdown_pct",
    "total_commission_usd",
    "signal_count",
    "selected_signal_count",
    "closed_trade_count",
    "open_trade_count",
    "winning_trade_count",
    "losing_trade_count",
    "source_watermark_utc",
    "analyser_watermark_utc",
    "source_market_table",
    "source_analyser_table",
    "price_basis",
    "entry_execution_model",
    "atr_exit_execution_model",
    "intraday_conflict_policy",
    "gap_execution_policy",
    "end_of_data_policy",
    "prior_high_price_field",
    "atr_method",
    "fractional_shares_allowed",
    "risk_equity_basis",
    "ranking_policy",
    "symbol_reentry_policy",
    "max_positions",
    "max_new_positions_per_day",
    "risk_per_position_pct",
    "initial_stop_loss_pct",
    "stop_step_interval_sessions",
    "stop_step_pct",
    "initial_take_profit_pct",
    "take_profit_step_interval_sessions",
    "take_profit_step_pct",
    "atr_period_sessions",
    "atr_day1_exit_max_pct",
    "atr_day2_exit_max_pct",
    "prior_high_lookback_sessions",
    "prior_high_max_above_signal_close_pct",
    "min_daily_price_change_pct",
    "max_daily_price_change_pct_exclusive",
    "min_volume_vs_sma21_ratio_exclusive",
    "commission_bps",
    "slippage_bps",
    "analyser_min_price_usd",
    "analyser_min_dollar_volume_usd",
    "analyser_rs_lookback_1_sessions",
    "analyser_rs_lookback_2_sessions",
    "analyser_rs_lookback_3_sessions",
    "analyser_rs_lookback_4_sessions",
    "analyser_rs_weight_1",
    "analyser_rs_weight_2",
    "analyser_rs_weight_3",
    "analyser_rs_weight_4",
    "analyser_rs_min",
    "analyser_ma200_trend_sessions",
    "analyser_min_above_52w_low_ratio",
    "analyser_min_near_52w_high_ratio",
)

SIGNAL_DECISION_PREFIX_COLUMNS = (
    "run_id",
    "signal_date",
    *IDENTITY_COLUMNS,
    "selection_rank",
    "decision",
    "selected",
    "prior_high_observation_count",
    "prior_max_adjusted_high",
    "prior_high_limit_adjusted_price",
    "account_equity_before_entry_usd",
    "available_cash_before_entry_usd",
    "risk_budget_usd",
    "risk_per_share_usd",
    "risk_sized_shares",
    "cash_limited_shares",
    "selected_shares",
    "entry_reference_price",
    "entry_fill_price",
    "entry_commission_usd",
)

SIGNAL_RESULT_COLUMNS = (*SIGNAL_DECISION_PREFIX_COLUMNS, *ANALYSER_PAYLOAD_COLUMNS)

TRADE_RESULT_COLUMNS = (
    "run_id",
    "trade_id",
    *IDENTITY_COLUMNS,
    "entry_date",
    "exit_date",
    "status",
    "exit_reason",
    "shares",
    "holding_sessions",
    "entry_reference_price",
    "entry_fill_price",
    "entry_notional_usd",
    "entry_commission_usd",
    "risk_budget_usd",
    "planned_initial_stop_loss_usd",
    "initial_stop_price",
    "initial_take_profit_price",
    "active_stop_price_at_exit",
    "active_take_profit_price_at_exit",
    "exit_reference_price",
    "exit_fill_price",
    "exit_notional_usd",
    "exit_commission_usd",
    "last_valuation_date",
    "last_mark_price",
    "market_value_usd",
    "gross_pnl_usd",
    "net_pnl_usd",
    "return_pct",
)

EQUITY_RESULT_COLUMNS = (
    "run_id",
    "valuation_date",
    "cash_usd",
    "positions_market_value_usd",
    "total_equity_usd",
    "realized_pnl_usd",
    "unrealized_pnl_usd",
    "cumulative_commission_usd",
    "open_position_count",
    "closed_trade_count",
    "daily_return_pct",
    "total_return_pct",
    "drawdown_pct",
)
